//
// Created by hoang on 2/21/2022.
//

#ifndef UNTITLED5_U_HARDWARE_INIT_H
#define UNTITLED5_U_HARDWARE_INIT_H

#include "U_platform.h"



#define U_GLOBAL_INTERRUPT_ENABLE()     BIT_SET(INTCON, GIE)
#define U_GLOBAL_INTERRUPT_DISABLE()    BIT_CLEAR(INTCON, GIE)

#define U_EXTERNAL_INTERRUPT_ENABLE() BIT_SET(INTCON, INTE)
#define U_EXTERNAL_INTERRUPT_DISABLE()  BIT_CLEAR(INTCON, INTE)

#define U_IS_SET_EXTERNAL_INTERRUPT()   BIT_READ(INTCON,INTF)
#define U_CLEAR_EXTERNAL_INTERRUPT()   BIT_CLEAR(INTCON,INTF)

#define U_EXTERNAL_INTERRUPT_FALLING()     BIT_SET(OPTION_REG, INTEDG)
#define U_EXTERNAL_INTERRUPT_RISING()      BIT_CLEAR(OPTION_REG, INTEDG)

 inline void InitTimer1();
 inline void InitExternalInterrupt();
 inline void U_gpioInit();




#endif //UNTITLED5_U_HARDWARE_INIT_H